export const regionMapping = {
  B: "Region 2 (Cagayan Valley)",
  C: "Region 3 (Central Luzon)",
  R: "Region 3 (Central Luzon)",
  W: "Region 3 (Central Luzon)",
  D: "Region 4A (CALABARZON)",
  O: "Region 4A (CALABARZON)",
  E: "Region 5 (Bicol Region)",
  F: "Region 6 (Western Visayas)",
  G: "Region 7 (Central Visayas)",
  H: "Region 8 (Eastern Visayas)",
  I: "Region 1 (Ilocos Region)",
  A: "Region 1 (Ilocos Region) (motorcycles only)",
  J: "Region 9 (Zamboanga Peninsula), Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)",
  K: "Region 10 (Northern Mindanao)",
  L: "Region 11 (Davao Region)",
  M: "Region 12 (SOCCSKSARGEN)",
  N: "National Capital Region (NCR)",
  P: "National Capital Region (NCR)",
  Q: "National Capital Region (NCR)",
  T: "National Capital Region (NCR)",
  U: "National Capital Region (NCR)",
  X: "National Capital Region (NCR)",
  S: "Government-owned vehicles",
  V: "Region 4B (MIMAROPA)",
  Y: "Cordillera Administrative Region (CAR)",
  Z: "Region 13 (Caraga)",
};

export const monthMapping = {
  1: "Jan",
  2: "Feb",
  3: "Mar",
  4: "Apr",
  5: "May",
  6: "Jun",
  7: "Jul",
  8: "Aug",
  9: "Sept",
  0: "Oct",
};

export const weekMapping = {
  1: "1st",
  2: "1st",
  3: "1st",
  4: "2nd",
  5: "2nd",
  6: "2nd",
  7: "3rd",
  8: "3rd",
  9: "4th",
  0: "4th",
};
